#!/usr/bin/sh 

realpath=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)

(echo "Disk"
echo "/ : $(df -h / | sed '1d' | awk '{print $3}')/$(df -h / | sed '1d' | awk '{print $2}')"
echo "/home: $(df -h /home | sed '1d' | awk '{print $3}')/$(df -h /home | sed '1d' | awk '{print $2}')"
) | dzen2 -p 4 -x "$(. $realpath/getmousepos)" -y "20" -w "200" -l "2" -sa 'c' -ta 'c' -e 'onstart=uncollapse;button1=exit;button3=exit' -fn  -*-ohsnapu-medium-r-normal-*-11-*-*-*-*-*-*-* 
